services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: bianca
      POSTGRES_PASSWORD: scrolllock
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: