<div>
    <section class="listing-header recipe-editor-header"><div class="container"><span class="eyebrow">Nova receita</span><h1>Vamos guardar uma nova receita?</h1><p>Preencha os detalhes para ela ficar sempre à mão.</p></div></section>
    <section class="section container recipe-editor"><form wire:submit="salvar('publicada')" enctype="multipart/form-data" class="recipe-form">
        <x-recipes.form-section number="01" title="Sobre a receita" description="Comece pelos detalhes que tornam esse preparo especial.">
            <div class="form-field form-field-wide"><label for="titulo">Título <span aria-hidden="true">*</span></label><input id="titulo" type="text" wire:model="titulo" placeholder="Ex.: Bolo de fubá da vovó" aria-required="true">@error('titulo')<small class="form-error">Dê um nome para sua receita.</small>@enderror</div>
            <div class="form-field form-field-wide"><label for="descricao">Descrição <span aria-hidden="true">*</span></label><textarea id="descricao" wire:model="descricao" rows="4" placeholder="Conte um pouco sobre essa receita..." aria-required="true"></textarea>@error('descricao')<small class="form-error">Conte um pouco mais sobre sua receita.</small>@enderror</div>
            <div class="form-field"><label for="categoria_id">Categoria <span aria-hidden="true">*</span></label><select id="categoria_id" wire:model="categoria_id" aria-required="true"><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->nome }}</option>@endforeach</select>@error('categoria_id')<small class="form-error">Escolha uma categoria.</small>@enderror</div>
            <div class="form-field recipe-upload-field"><label for="foto">Foto da receita</label><input id="foto" type="file" wire:model="foto" accept="image/jpeg,image/png,image/webp"><span wire:loading wire:target="foto" class="upload-status">Enviando imagem...</span>@if($foto)<img class="recipe-upload-preview" src="{{ $foto->temporaryUrl() }}" alt="Prévia da foto selecionada">@endif @error('foto')<small class="form-error">Escolha uma imagem JPG, PNG ou WEBP de até 5 MB.</small>@enderror<small>JPG, PNG ou WEBP · até 5 MB</small></div>
        </x-recipes.form-section>
        <x-recipes.form-section number="02" title="Ingredientes" description="Liste tudo o que você precisa, na ordem que preferir.">
            <div class="form-field form-field-wide ingredients-field"><div class="field-heading"><label>Ingredientes <span aria-hidden="true">*</span></label><button type="button" wire:click="adicionarIngrediente" wire:loading.attr="disabled" wire:target="adicionarIngrediente" class="text-link">＋ Adicionar ingrediente</button></div><div class="ingredient-headings" aria-hidden="true"><span>Ingrediente</span><span>Quantidade</span><span>Unidade</span><span>Observação</span></div>@foreach($ingredientes as $indice => $ingrediente)<div wire:key="ingrediente-{{ $ingrediente['chave'] ?? $indice }}" class="ingredient-item"><div class="ingredient-row"><input type="text" wire:model="ingredientes.{{ $indice }}.nome" placeholder="Ex.: farinha de trigo" aria-label="Nome do ingrediente {{ $indice + 1 }}"><input type="number" step="0.01" min="0" wire:model="ingredientes.{{ $indice }}.quantidade" placeholder="Qtd." aria-label="Quantidade do ingrediente {{ $indice + 1 }}"><select wire:model="ingredientes.{{ $indice }}.unidade" aria-label="Unidade do ingrediente {{ $indice + 1 }}"><option value="unidade">unidade</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="l">l</option><option value="xicara">xícara</option><option value="colher_sopa">colher de sopa</option><option value="colher_cha">colher de chá</option><option value="a_gosto">a gosto</option></select><input type="text" wire:model="ingredientes.{{ $indice }}.observacao" placeholder="Observação" aria-label="Observação do ingrediente {{ $indice + 1 }}"><button type="button" wire:click="removerIngrediente({{ $indice }})" class="remove-ingredient" aria-label="Remover ingrediente {{ $indice + 1 }}">×</button></div>@error("ingredientes.$indice.nome")<small class="form-error">Informe o ingrediente.</small>@enderror</div>@endforeach</div>
        </x-recipes.form-section>
        <x-recipes.form-section number="03" title="Modo de preparo" description="Escreva o passo a passo do seu jeito.">
            <div class="form-field form-field-wide"><label for="modo_preparo">Modo de preparo <span aria-hidden="true">*</span></label><textarea id="modo_preparo" wire:model="modo_preparo" rows="10" placeholder="Descreva o preparo passo a passo..." aria-required="true"></textarea>@error('modo_preparo')<small class="form-error">Descreva o preparo com um pouco mais de detalhes.</small>@enderror</div>
        </x-recipes.form-section>
        <x-recipes.form-section number="04" title="Tempo e rendimento" description="Ajude seu futuro eu a planejar o preparo.">
            <div class="form-field"><label for="tempo_preparo_min">Preparo (min) <span aria-hidden="true">*</span></label><input id="tempo_preparo_min" type="number" wire:model="tempo_preparo_min" min="1" aria-required="true"></div><div class="form-field"><label for="tempo_cozimento_min">Cozimento (min)</label><input id="tempo_cozimento_min" type="number" wire:model="tempo_cozimento_min" min="0"></div><div class="form-field"><label for="porcoes">Porções <span aria-hidden="true">*</span></label><input id="porcoes" type="number" wire:model="porcoes" min="1" aria-required="true"></div>
        </x-recipes.form-section>
        <x-recipes.form-section number="05" title="Detalhes" description="Alguns detalhes ajudam a lembrar como essa receita funciona.">
            <div class="form-field"><label for="dificuldade">Dificuldade <span aria-hidden="true">*</span></label><select id="dificuldade" wire:model="dificuldade"><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option></select></div><div class="form-field"><label for="custo">Custo <span aria-hidden="true">*</span></label><select id="custo" wire:model="custo"><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option></select></div>
        </x-recipes.form-section>
        <div class="form-actions recipe-editor-actions"><a href="{{ route('minhas-receitas') }}" class="text-link">Cancelar</a><button type="button" wire:click="salvar('rascunho')" wire:loading.attr="disabled" wire:target="salvar" class="button button-outline"><span wire:loading.remove wire:target="salvar">Salvar rascunho</span><span wire:loading wire:target="salvar">Salvando...</span></button><button type="submit" wire:loading.attr="disabled" wire:target="salvar" class="button"><span wire:loading.remove wire:target="salvar">Publicar receita <span>→</span></span><span wire:loading wire:target="salvar">Publicando...</span></button></div>
    </form></section>
</div>
