<div>
    <section class="listing-header"><div class="container"><span class="eyebrow">Compartilhe seu sabor</span><h1>Nova receita</h1><p>Guarde uma receita especial no nosso caderno.</p></div></section>
    <section class="section container"><form wire:submit="salvar('publicada')" enctype="multipart/form-data" class="recipe-form">
        <div class="form-intro"><div><span class="eyebrow">Detalhes principais</span><h2>Conte como se faz</h2></div><span class="form-required">* campos obrigatórios</span></div>
        <div class="form-field form-field-wide"><label for="titulo">Título *</label><input id="titulo" type="text" wire:model="titulo" placeholder="Ex.: Bolo de fubá da vovó">@error('titulo')<small class="form-error">{{ $message }}</small>@enderror</div>
        <div class="form-field form-field-wide"><label for="descricao">Descrição *</label><textarea id="descricao" wire:model="descricao" rows="4" placeholder="Conte um pouco sobre essa receita..."></textarea>@error('descricao')<small class="form-error">{{ $message }}</small>@enderror</div>
        <div class="form-field"><label for="categoria_id">Categoria *</label><select id="categoria_id" wire:model="categoria_id"><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->nome }}</option>@endforeach</select>@error('categoria_id')<small class="form-error">{{ $message }}</small>@enderror</div>
        <div class="form-field recipe-upload-field"><label for="foto">Foto da receita</label><input id="foto" type="file" wire:model="foto" accept="image/*"><span wire:loading wire:target="foto" class="upload-status">Enviando imagem...</span>@if($foto)<img class="recipe-upload-preview" src="{{ $foto->temporaryUrl() }}" alt="Prévia da foto">@endif @error('foto')<small class="form-error">{{ $message }}</small>@enderror<small>Selecione uma imagem JPG, PNG ou WEBP de até 5 MB.</small></div>
        <div class="form-field form-field-wide ingredients-field"><div class="field-heading"><label>Ingredientes *</label><button type="button" wire:click="adicionarIngrediente" wire:loading.attr="disabled" wire:target="adicionarIngrediente" class="text-link">+ Adicionar ingrediente</button></div>@foreach($ingredientes as $indice => $ingrediente)<div wire:key="ingrediente-{{ $ingrediente['chave'] ?? $indice }}" class="ingredient-item"><div class="ingredient-row"><input type="text" wire:model="ingredientes.{{ $indice }}.nome" placeholder="Ex.: farinha de trigo"><input type="number" step="0.01" min="0" wire:model="ingredientes.{{ $indice }}.quantidade" placeholder="Qtd."><select wire:model="ingredientes.{{ $indice }}.unidade"><option value="unidade">unidade</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="l">l</option><option value="xicara">xícara</option><option value="colher_sopa">colher de sopa</option><option value="colher_cha">colher de chá</option><option value="a_gosto">a gosto</option></select><input type="text" wire:model="ingredientes.{{ $indice }}.observacao" placeholder="Observação"><button type="button" wire:click="removerIngrediente({{ $indice }})" class="remove-ingredient" aria-label="Remover ingrediente">×</button></div>@error("ingredientes.$indice.nome")<small class="form-error">{{ $message }}</small>@enderror</div>@endforeach</div>
        <div class="form-field form-field-wide"><label for="modo_preparo">Modo de preparo *</label><textarea id="modo_preparo" wire:model="modo_preparo" rows="8" placeholder="Descreva o preparo passo a passo..."></textarea>@error('modo_preparo')<small class="form-error">{{ $message }}</small>@enderror</div>
        <div class="form-field"><label for="tempo_preparo_min">Preparo (min) *</label><input id="tempo_preparo_min" type="number" wire:model="tempo_preparo_min" min="1"></div><div class="form-field"><label for="tempo_cozimento_min">Cozimento (min)</label><input id="tempo_cozimento_min" type="number" wire:model="tempo_cozimento_min" min="0"></div><div class="form-field"><label for="porcoes">Porções *</label><input id="porcoes" type="number" wire:model="porcoes" min="1"></div><div class="form-field"><label for="dificuldade">Dificuldade *</label><select id="dificuldade" wire:model="dificuldade"><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option></select></div><div class="form-field"><label for="custo">Custo *</label><select id="custo" wire:model="custo"><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option></select></div>
        <div class="form-actions"><a href="{{ route('inicio') }}" class="text-link">Cancelar</a><button type="button" wire:click="salvar('rascunho')" wire:loading.attr="disabled" wire:target="salvar" class="button button-outline"><span wire:loading.remove wire:target="salvar">Salvar rascunho</span><span wire:loading wire:target="salvar">Salvando...</span></button><button type="submit" wire:loading.attr="disabled" wire:target="salvar" class="button"><span wire:loading.remove wire:target="salvar">Publicar receita <span>→</span></span><span wire:loading wire:target="salvar">Publicando...</span></button></div>
    </form></section>
</div>
