<div>
    <section class="account-header"><div class="container"><span class="eyebrow">Seu caderno</span><h1>Editar receita</h1><p>Ajuste os detalhes e mantenha sua receita sempre atualizada.</p></div></section>
    <section class="section container">
        <form wire:submit="salvar" class="recipe-form">
            <div class="form-intro"><div><span class="eyebrow">Atualização</span><h2>{{ $receita->titulo }}</h2></div><span class="form-required">* campos obrigatórios</span></div>
            @if(session('sucesso'))<div class="success-message form-field-wide" role="status" aria-live="polite">{{ session('sucesso') }}</div>@endif
            <div class="form-field form-field-wide"><label for="titulo">Título *</label><input id="titulo" type="text" wire:model="titulo">@error('titulo')<small class="form-error">{{ $message }}</small>@enderror</div>
            <div class="form-field form-field-wide"><label for="descricao">Descrição *</label><textarea id="descricao" wire:model="descricao" rows="4"></textarea>@error('descricao')<small class="form-error">{{ $message }}</small>@enderror</div>
            <div class="form-field"><label for="categoria_id">Categoria *</label><select id="categoria_id" wire:model="categoria_id"><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->nome }}</option>@endforeach</select>@error('categoria_id')<small class="form-error">{{ $message }}</small>@enderror</div>
            <div class="form-field recipe-upload-field"><label for="foto">Foto da receita</label><input id="foto" type="file" wire:model="foto" accept="image/*"><span wire:loading wire:target="foto" class="upload-status">Enviando imagem...</span>@if($foto)<img class="recipe-upload-preview" src="{{ $foto->temporaryUrl() }}" alt="Prévia da nova foto">@elseif($receita->foto_url)<img class="recipe-upload-preview" src="{{ $receita->foto_url }}" alt="Foto atual da receita">@endif @error('foto')<small class="form-error">{{ $message }}</small>@enderror<small>Selecione uma imagem JPG, PNG ou WEBP de até 5 MB.</small></div>
            <div class="form-field form-field-wide ingredients-field"><div class="field-heading"><label>Ingredientes *</label><button type="button" wire:click="adicionarIngrediente" wire:loading.attr="disabled" wire:target="adicionarIngrediente" class="text-link">+ Adicionar ingrediente</button></div>@foreach($ingredientes as $indice => $ingrediente)<div wire:key="ingrediente-{{ $ingrediente['chave'] ?? $indice }}" class="ingredient-item"><div class="ingredient-row"><input type="text" wire:model="ingredientes.{{ $indice }}.nome" placeholder="Ex.: farinha de trigo"><input type="number" step="0.01" min="0" wire:model="ingredientes.{{ $indice }}.quantidade" placeholder="Qtd."><select wire:model="ingredientes.{{ $indice }}.unidade"><option value="unidade">unidade</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="l">l</option><option value="xicara">xícara</option><option value="colher_sopa">colher de sopa</option><option value="colher_cha">colher de chá</option><option value="a_gosto">a gosto</option></select><input type="text" wire:model="ingredientes.{{ $indice }}.observacao" placeholder="Observação"><button type="button" wire:click="removerIngrediente({{ $indice }})" class="remove-ingredient" aria-label="Remover ingrediente">×</button></div>@error("ingredientes.$indice.nome")<small class="form-error">{{ $message }}</small>@enderror</div>@endforeach</div>
            <div class="form-field form-field-wide"><label for="modo_preparo">Modo de preparo *</label><textarea id="modo_preparo" wire:model="modo_preparo" rows="8" placeholder="Descreva o preparo passo a passo..."></textarea>@error('modo_preparo')<small class="form-error">{{ $message }}</small>@enderror</div>
            <div class="form-field form-field-wide"><label for="tipo_fonte">Origem da receita</label><select id="tipo_fonte" wire:model="tipo_fonte"><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="site">Site</option><option value="livro">Livro</option><option value="familia">Família</option><option value="minha_receita">Minha receita</option><option value="outro">Outro</option></select></div><div class="form-field"><label for="nome_fonte">Nome da fonte</label><input id="nome_fonte" type="text" wire:model="nome_fonte" placeholder="Ex.: Caderno da vó"></div><div class="form-field"><label for="url_fonte">Link original</label><input id="url_fonte" type="url" wire:model="url_fonte" placeholder="https://...">@error('url_fonte')<small class="form-error">{{ $message }}</small>@enderror</div><div class="form-field form-field-wide"><label for="observacoes_pessoais">Minhas observações</label><textarea id="observacoes_pessoais" wire:model="observacoes_pessoais" rows="4" placeholder="O que lembrar na próxima vez?"></textarea></div>
            <div class="form-field"><label for="tempo_preparo_min">Preparo (min) *</label><input id="tempo_preparo_min" type="number" wire:model="tempo_preparo_min" min="1"></div><div class="form-field"><label for="tempo_cozimento_min">Cozimento (min)</label><input id="tempo_cozimento_min" type="number" wire:model="tempo_cozimento_min" min="0"></div><div class="form-field"><label for="porcoes">Porções *</label><input id="porcoes" type="number" wire:model="porcoes" min="1"></div><div class="form-field"><label for="dificuldade">Dificuldade *</label><select id="dificuldade" wire:model="dificuldade"><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option></select></div><div class="form-field"><label for="custo">Custo *</label><select id="custo" wire:model="custo"><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option></select></div>
            <div class="form-actions"><a class="text-link" href="{{ route('minhas-receitas') }}">Cancelar</a><button class="button" type="submit" wire:loading.attr="disabled" wire:target="salvar"><span wire:loading.remove wire:target="salvar">Salvar alterações <span>→</span></span><span wire:loading wire:target="salvar">Salvando...</span></button></div>
        </form>
    </section>
</div>
