@extends('layouts.public')

@section('title', 'Receitas — Cantinho das Receitas')
@section('description', 'Encontre receitas caseiras, organize suas descobertas e escolha o que cozinhar hoje no Cantinho das Receitas.')

@section('content')
<section class="listing-header"><div class="container"><span class="eyebrow">Nosso caderno</span><h1>Todas as receitas</h1><p>Escolha uma receita e deixe a cozinha cuidar do resto.</p><form action="{{ route('receitas.listar') }}" method="GET" class="search-form listing-search"><span aria-hidden="true">⌕</span><input name="busca" value="{{ $term }}" type="search" placeholder="Buscar por nome, categoria ou ingrediente..." aria-label="Buscar receitas"><button type="submit">Buscar</button></form></div></section>
<section class="section container"><form action="{{ route('receitas.listar') }}" method="GET" class="catalog-filters" aria-label="Filtrar receitas"><input type="hidden" name="busca" value="{{ $term }}"><label>Categoria<select name="categoria"><option value="">Todas</option>@foreach ($categorias as $categoria)<option value="{{ $categoria['name'] }}" @selected(($filtros['categoria'] ?? '') === $categoria['name'])>{{ $categoria['name'] }}</option>@endforeach</select></label><label>Dificuldade<select name="dificuldade"><option value="">Todas</option><option value="facil" @selected(($filtros['dificuldade'] ?? '') === 'facil')>Fácil</option><option value="medio" @selected(($filtros['dificuldade'] ?? '') === 'medio')>Médio</option><option value="dificil" @selected(($filtros['dificuldade'] ?? '') === 'dificil')>Difícil</option></select></label><label>Tempo<select name="tempo"><option value="">Qualquer tempo</option><option value="30" @selected(($filtros['tempo'] ?? '') === '30')>Até 30 min</option><option value="60" @selected(($filtros['tempo'] ?? '') === '60')>Até 1 hora</option></select></label><label>Ordenar<select name="ordenar"><option value="recentes" @selected(($filtros['ordenar'] ?? 'recentes') === 'recentes')>Mais recentes</option><option value="antigas" @selected(($filtros['ordenar'] ?? '') === 'antigas')>Mais antigas</option><option value="avaliadas" @selected(($filtros['ordenar'] ?? '') === 'avaliadas')>Mais bem avaliadas</option><option value="populares" @selected(($filtros['ordenar'] ?? '') === 'populares')>Mais populares</option><option value="alfabetica" @selected(($filtros['ordenar'] ?? '') === 'alfabetica')>Ordem alfabética</option></select></label><button class="button button-small" type="submit">Aplicar filtros</button>@if(collect($filtros)->filter()->isNotEmpty() || $term)<a class="text-link" href="{{ route('receitas.listar') }}">Limpar filtros</a>@endif</form><div class="section-heading"><div><span class="eyebrow">{{ count($recipes) }} {{ count($recipes) === 1 ? 'receita encontrada' : 'receitas encontradas' }}</span><h2>{{ $term ? 'Resultados para “'.$term.'”' : 'Inspire-se hoje' }}</h2></div><a class="text-link" href="{{ route('inicio') }}">← Voltar ao início</a></div>@if (count($recipes))<div class="recipe-grid">@foreach ($recipes as $recipe)<x-recipe-card :recipe="$recipe" />@endforeach</div>@else<div class="empty-state"><span aria-hidden="true">⌁</span><h2>Hmm... não encontramos essa receita.</h2><p>Tente outro nome, ingrediente ou categoria.</p><a class="button" href="{{ route('receitas.listar') }}">Limpar busca</a></div>@endif</section>
@endsection
